# Generated by Django 3.1 on 2020-08-30 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200830_1212'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '태그', 'verbose_name_plural': '태그'},
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_starts', models.DateField()),
                ('date_ends', models.DateField()),
                ('is_complete', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='plans.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정',
            },
        ),
        migrations.CreateModel(
            name='BucketList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('importance', models.IntegerField(choices=[(1, '매우 중요하지 않음'), (2, '중요하지 않음'), (3, '중간'), (4, '중요함'), (5, '매우 중요함')], default=3)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '하고 싶은 일',
                'verbose_name_plural': '하고 싶은 일',
            },
        ),
    ]
