# Generated by Django 3.1 on 2020-08-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20200830_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='importance',
            field=models.IntegerField(choices=[(0, '매우 중요하지 않음'), (1, '중요하지 않음'), (2, '중간'), (3, '중요함'), (4, '매우 중요함')], default=2),
        ),
    ]
